### ISSUE TITLE
README.md file needs to be updated with "How to run this file". 

### ISSUE THREAD

**Issue by akashfoss** [bitcraft/pyweek14#1]
Hey, I was just curious to run this game in my system but I am not able to run this game in my system by just running the run.py file. I think it needs something else too, so can you please update the README.md file just to make sure that the user can run it easily. Thanks.

**Comment by bitcraft** [comment]
Please respond with a trace back, your operating system, and the version of Python that you are using.

**Comment by akashfoss** [comment]
I am using an ubuntu 16.04 LTS version with the latest python (i.e 3.6, I guess).

**Comment by bitcraft** [comment]
This is a really old game, written when Python 2.7 was dominate and default.  I don't feel compelled to update it.  You should be able to run it fine with Python 2.7, as described in the readme.

**Comment by akashfoss** [comment]
I tried with python 2.7 too, the same thing is happening again.

**Comment by bitcraft** [comment]
Please respond with a traceback

**Comment by akashfoss** [comment]
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from lib2d.game import Game
  File "/home/akash/GitGames/pyweek14/lib2d/game.py", line 3, in <module>
    from lib2d import res
  File "/home/akash/GitGames/pyweek14/lib2d/res.py", line 28, in <module>
    import pygame
ImportError: No module named pygame

**Comment by bitcraft** [comment]
Install pygame and try again

**Comment by akashfoss** [comment]
Cool, it worked. It so cool, thanks for helping me out. :+1:
